Update Kotlin to `1.5.32` (#45)
* Update Kotlin to `1.6.21`

* Fix `java.lang.NoSuchMethodError: No virtual method elapsedNow-UwyO8pc()D in class Lkotlin/time/TimeMark;`

See: https://github.com/InsertKoinIO/koin/issues/1076

* Downgrade Kotlin `1.5.32`

Koin v2 (<v3) seems to be incompatible with Kotlin v1.6.

See: https://github.com/InsertKoinIO/koin/issues/1188

* Fix missing Type `T` in `observers.remove`